### ISSUE TITLE
Use type="number" for numerical inputs

### ISSUE THREAD

**Issue by wraybowling** [bieber/dovetails#1]
Your inputs are using plain text which allows full alphabet of characters. Instead, use [number inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). You'll get

- only valid numbers
- a way to set a minimum value
- up/down arrows on some browsers
- fixed precision that matches the origin's abilities

example `<input type="number" step="0.001" min="0.1" />`

**Comment by bieber** [comment]
Hm, sounds like ten minutes spent reading the docs on the new (how many years after HTML5 came out can I still keep calling them "new?") input types I could have saved myself a lot of grief manually implementing the validation. I'll have a look at this, thanks

**Comment by bieber** [comment]
Implemented in latest commit
