### ISSUE TITLE
Readily usable default values

### ISSUE THREAD

**Issue by wraybowling** [bieber/dovetails#2]
Should users read the instructions? absolutely. Will all of them actually read the instructions? No. Many users will try to just poke at the interface to see how it works. To better illustrate, give the app default settings so that when it's launched for the first time, settings show dovetails that could be readily used on a common piece of wood for a common dovetail bit. Let users adjust from there.

**Comment by bieber** [comment]
I've been thinking about this, and I think some kind of NUX, maybe in the form of tooltips on first visit or something similar, _would_ be a good idea but it's just not something I'm going to prioritize the free time to implement.  I'd be glad to accept the contribution if someone else wants to do it, but as long as it's just me I'll leave it as-is
