### ISSUE TITLE
units

### ISSUE THREAD

**Issue by rwyoungku** [bieber/dovetails#3]
Just starting to make a few screen-grabs to show where displaying units might be helpful. 

First one is the tooltip that floats over the "new pin width" box. I've switched to Imperial units but the tool tip value is in mm. Took me a hot minute to realize that first time.

![units](https://user-images.githubusercontent.com/6579169/133273451-8531bd4e-6198-4bc1-8f29-9b6a9fe86830.png)

**Comment by bieber** [comment]
Fixed in ee5e522a1b2946c5474b3fbdc2c046c999aa5125, which should be live in the next day or two
