### ISSUE TITLE
BUG: Reset pin height on Dovetail Type selection

### ISSUE THREAD

**Issue by jfrazier00** [bieber/dovetails#6]
When switching back and forth between Dovetail Type of "Half-Blind" and "Through" the pin height is ever-shrinking. ;)

Steps:
- Refresh page to default
- Set "Pin Count" to some number like 2
- Click "Auto Layout"
- Change Dovetail Type to "Half-Blind"
- Change Dovetail Type to "Through"
- Repeat last two steps a few times for good measure

Observe shrinking pins

**Comment by bieber** [comment]
This is actually a punishment for indecisive users ;)

Seriously though, I'll try to get an update in for it one of these days.  It's something I didn't think anyone would really notice in my excitement to have half blind mode actually working, and it looks like I underestimated the amount of clicking around people will do :D

**Comment by jfrazier00** [comment]
Hahaha. Been in software biz for a very long time and get it. I coined a term lifted from a David letterman bit… instead of “Stupid Pet Tricks”… I would refer to them as “Stupid User Tricks”. 🤣

Thanks a ton for your work on this tool and the docs. I am just getting ready for first cuts and will post up to the Shaper forums with success/notes.

**Comment by bieber** [comment]
I was just making another fix today and realized this was still open, so I went ahead and fixed it up in 952d194
