### ISSUE TITLE
need extra width to get 1/2 pins to cut

### ISSUE THREAD

**Issue by rwyoungku** [bieber/dovetails#7]
I need to edit the SVGs for the tail file to add extra width to the path on the far left and far right so that a 17/32 DT bit will cut the half-pin voids.

Haven't bothered to calculate HOW much extra I need, just edited the SVG to add a 1/2" wide rectangle at each end, joined to the path and then touched up the color encoding again to make it a single pocket cut.

These are somewhat narrow 1/2 pins, only about 0.2" wide at the base.

**Comment by rwyoungku** [comment]
forgot to add the link so you can see design settings:

[https://dovetails.bieber.dev/?s=eyJnZW5lcmFsIjp7ImtpbmQiOiJ0aHJvdWdoIiwidW5pdCI6ImluY2giLCJjdXR0ZXIiOnsiZG92ZXRhaWxEaWFtZXRlciI6MTMuNDkzNzUsInN0cmFpZ2h0RGlhbWV0ZXIiOjYuMzUsImhlaWdodCI6MTkuODQzNzUsImFuZ2xlIjo3fSwibWF0ZXJpYWwiOnsidGhpY2tuZXNzIjoxMi45NTQsIndpZHRoIjoxNjAuNDUxOCwiZG92ZXRhaWxMZW5ndGgiOjEyLjk1NH19LCJndWlkZXMiOnsiZW5hYmxlZCI6dHJ1ZSwic3BhY2luZyI6My4xNzUsImZyb20iOiJjZW50ZXIifSwiaGFsZlBpbnMiOnsiZW5hYmxlZCI6dHJ1ZSwid2lkdGgiOjUuMDh9LCJwaW5zIjpbeyJpZCI6MTMyLCJzZWxlY3RlZCI6ZmFsc2UsIngiOjI5LjU5ODQ0OTU5OTM1NDU4OCwibWF4V2lkdGgiOjE4LjQ2NjM2ODAwMjE1MTM2fSx7ImlkIjoxMzQsInNlbGVjdGVkIjpmYWxzZSwieCI6NjMuMzUwMDgzMTk5Nzg0ODU1LCJtYXhXaWR0aCI6MTguNDY2MzY4MDAyMTUxMzZ9LHsiaWQiOjEzNiwic2VsZWN0ZWQiOmZhbHNlLCJ4Ijo5Ny4xMDE3MTY4MDAyMTUxMiwibWF4V2lkdGgiOjE4LjQ2NjM2ODAwMjE1MTM2fSx7ImlkIjoxMzgsInNlbGVjdGVkIjpmYWxzZSwieCI6MTMwLjg1MzM1MDQwMDY0NTM4LCJtYXhXaWR0aCI6MTguNDY2MzY4MDAyMTUxMzZ9XX0=](url)

**Comment by bieber** [comment]
Thanks for the report, I'll try to figure out what's causing this in the next couple days

**Comment by rwyoungku** [comment]
Let me know if you want some SVGs from "as generated" vs. "as edited" to further explain what I observed. I can probably snap some photos of the SO screen with the various files if needed.

**Comment by bieber** [comment]
No worries, I found the problem already.  It looks like I just made the cut area extend out to 1.1 * the cutter radius without considering that it wouldn't be sufficient for thin half pins

**Comment by bieber** [comment]
Fixed in 5a009d0ebda026b4fc4847328ff240b2e2fe7e76 and updated.  @rwyoungku this should be good to go in production, but to be safe you may want to reload without cache (ctrl-shift-r in Chrome) to make sure you're not getting a cached copy.  Let me know if you still have any problems

**Comment by rwyoungku** [comment]
Great! I'll give it a test later today or Friday morning.

Thanks for your help.

**Comment by rwyoungku** [comment]
Seems to be broken now. Attached the link to what I used to generate a file. Also a copy of the tails SVG, a quick screen cap showing the overlapping paths after stripping out the guide and anchor as well as a picture of the SO screen.


https://dovetails.bieber.dev/?s=eyJnZW5lcmFsIjp7ImtpbmQiOiJ0aHJvdWdoIiwidW5pdCI6ImluY2giLCJjdXR0ZXIiOnsiZG92ZXRhaWxEaWFtZXRlciI6Ny45Mzc1LCJzdHJhaWdodERpYW1ldGVyIjo2LjM1LCJoZWlnaHQiOjE2LjY2ODc1LCJhbmdsZSI6N30sIm1hdGVyaWFsIjp7InRoaWNrbmVzcyI6MTMuMjA4LCJ3aWR0aCI6MTYxLjU0NCwiZG92ZXRhaWxMZW5ndGgiOjEwfX0sImd1aWRlcyI6eyJlbmFibGVkIjp0cnVlLCJzcGFjaW5nIjozLjE3NSwiZnJvbSI6ImNlbnRlciJ9LCJoYWxmUGlucyI6eyJlbmFibGVkIjp0cnVlLCJ3aWR0aCI6Ni4zNX0sInBpbnMiOlt7ImlkIjo2NCwic2VsZWN0ZWQiOmZhbHNlLCJ4Ijo4MC43NzIsIm1heFdpZHRoIjo4Ljg5fSx7ImlkIjo2OCwic2VsZWN0ZWQiOmZhbHNlLCJ4IjoxMjAuMjA1NTAwMDAwMDAwMDEsIm1heFdpZHRoIjo4Ljg5fSx7ImlkIjo3Miwic2VsZWN0ZWQiOnRydWUsIngiOjQxLjMzODUsIm1heFdpZHRoIjo4Ljg5fV19





![tails](https://user-images.githubusercontent.com/6579169/210103313-8030c42c-6362-4807-b75a-8d6dcf77b832.svg)
![broken_path](https://user-images.githubusercontent.com/6579169/210103334-76739156-69d1-432a-927b-5b90f341217c.png)
![20221230_124726](https://user-images.githubusercontent.com/6579169/210103413-2bb6ed7a-192d-43e7-9fbb-20ad7fded7e1.jpg)
