### ISSUE TITLE
Seems to be broken now. Attached the link to what I used to generate a file. Also a copy of the tails SVG, a quick screen cap showing the overlapping paths after stripping out the guide and anchor as well as a picture of the SO screen.

### ISSUE THREAD

**Issue by rwyoungku** [bieber/dovetails#8]
Seems to be broken now. Attached the link to what I used to generate a file. Also a copy of the tails SVG, a quick screen cap showing the overlapping paths after stripping out the guide and anchor as well as a picture of the SO screen.

https://dovetails.bieber.dev/?s=eyJnZW5lcmFsIjp7ImtpbmQiOiJ0aHJvdWdoIiwidW5pdCI6ImluY2giLCJjdXR0ZXIiOnsiZG92ZXRhaWxEaWFtZXRlciI6Ny45Mzc1LCJzdHJhaWdodERpYW1ldGVyIjo2LjM1LCJoZWlnaHQiOjE2LjY2ODc1LCJhbmdsZSI6N30sIm1hdGVyaWFsIjp7InRoaWNrbmVzcyI6MTMuMjA4LCJ3aWR0aCI6MTYxLjU0NCwiZG92ZXRhaWxMZW5ndGgiOjEwfX0sImd1aWRlcyI6eyJlbmFibGVkIjp0cnVlLCJzcGFjaW5nIjozLjE3NSwiZnJvbSI6ImNlbnRlciJ9LCJoYWxmUGlucyI6eyJlbmFibGVkIjp0cnVlLCJ3aWR0aCI6Ni4zNX0sInBpbnMiOlt7ImlkIjo2NCwic2VsZWN0ZWQiOmZhbHNlLCJ4Ijo4MC43NzIsIm1heFdpZHRoIjo4Ljg5fSx7ImlkIjo2OCwic2VsZWN0ZWQiOmZhbHNlLCJ4IjoxMjAuMjA1NTAwMDAwMDAwMDEsIm1heFdpZHRoIjo4Ljg5fSx7ImlkIjo3Miwic2VsZWN0ZWQiOnRydWUsIngiOjQxLjMzODUsIm1heFdpZHRoIjo4Ljg5fV19

![tails](https://user-images.githubusercontent.com/6579169/210103313-8030c42c-6362-4807-b75a-8d6dcf77b832.svg)
![broken_path](https://user-images.githubusercontent.com/6579169/210103334-76739156-69d1-432a-927b-5b90f341217c.png)
![20221230_124726](https://user-images.githubusercontent.com/6579169/210103413-2bb6ed7a-192d-43e7-9fbb-20ad7fded7e1.jpg)

_Originally posted by @rwyoungku in https://github.com/bieber/dovetails/issues/7#issuecomment-1368051091_

**Comment by bieber** [comment]
Huh, this was a weird bug unrelated to the edge spacing thing, I'm actually surprised it hasn't cropped up before.  I just pushed a change that should fix it, let me know if you have any further problems

**Comment by rwyoungku** [comment]
Testing now... :)

**Comment by rwyoungku** [comment]
Test of through dovetails was OK. I'll check the HB later. Working on 6 drawers...

**Comment by rwyoungku** [comment]
Made a test file for HB and it fits. Only tested the "A" files but quick look at the "B" files in InkScape and they look right.

Thanks again!
