### ISSUE TITLE
Can not download templates

### ISSUE THREAD

**Issue by jfelix529** [bieber/dovetails#9]
![data](https://github.com/bieber/dovetails/assets/169055216/424bf208-5026-40cf-8cde-b011d47dd2b8)
After I set up the dovetail files I'm unable to download the templates. It goes to a data page.

**Comment by bieber** [comment]
I set the data link up to default to download, but some browsers may not respect that.  You can either save the page you're on with Ctrl-s or Cmd-s, or instead of clicking the download buttons right click and save-as
